// Design tokens extracted from design-reference/mobile/*.html (Stitch mobile design system).
export const Colors = {
  primary: "#000000",
  onPrimary: "#ffffff",
  primaryContainer: "#131b2e",
  secondary: "#0051d5",
  onSecondary: "#ffffff",
  secondaryContainer: "#316bf3",
  onSecondaryContainer: "#fefcff",
  secondaryFixed: "#dbe1ff",
  onSecondaryFixed: "#00174b",
  background: "#f8f9ff",
  surface: "#f8f9ff",
  surfaceContainerLowest: "#ffffff",
  surfaceContainerLow: "#eff4ff",
  surfaceContainer: "#e5eeff",
  surfaceContainerHigh: "#dce9ff",
  surfaceContainerHighest: "#d3e4fe",
  onSurface: "#0b1c30",
  onSurfaceVariant: "#45464d",
  outline: "#76777d",
  outlineVariant: "#c6c6cd",
  error: "#ba1a1a",
  onError: "#ffffff",
  errorContainer: "#ffdad6",
  onErrorContainer: "#93000a",
  tertiaryContainer: "#002114",
  onTertiaryContainer: "#069669",
} as const;
